version: "3.3"
services:
  www:
    build: ./config
    ports:
      - "80:80"
    restart: always
    volumes:
      - /var/www/html/:/var/www/html/
    links:
      - db
    networks:
      - default

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    restart: always
    volumes:
      - persistent:/var/lib/mysql
      - ./config/mysql:/docker-entrypoint-initdb.d/:ro
    networks:
      - default

volumes:
  persistent: